---
title: "Dinner"
author: "Audrey Commerford"
date: "2025-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Harissa chickpeas + naan + tzatziki + cucumber 

Shakshuka + eggs + bread

Farro + cucumber + chickpeas + feta + sunflower seeds 

Pasta + cherry tomatoes + basil + mozzarella 

Sweet potato tacos: Corn tortillas + sweet potato + black beans + avocado lime yogurt sauce + feta 

Tofu + snap peas + bell pepper + rice + soy sauce 

Green beans + rice + soft boiled eggs + sriracha 

fajitas: Mini flour tortillas + bell pepper + yellow onion + portobello mushroom + taco season + black beans/refried beans 

Sesame ginger chickpeas + rice + stir fried veggies (broccoli + red bell pepper)

Farro + celery + northern white beans + apple + dates + nuts + feta + maple vinaigrette 

Butter cauliflower: Roasted cauliflower + butter chicken sauce + chickpeas + rice + cilantro mint yogurt sauce 

Cuban black beans + avocado + tortilla chips + lime + cilantro

# Lazy Meals
Tortilla + black beans + cheese + salsa/guac 

Dragon noodles: Instant noodles + scrambled egg and/or tofu + sriracha + honey/brown sugar + soy sauce 

Frozen gyoza + soy sauce 

Bread + cheese + tomato soup 

Sautéed mushroom + spinach + egg + toast 

Farro + feta + soft boiled egg 

Frozen fried rice + scrambled egg or tofu